export const skills: SkillCategory[] = [
  {
    id: "frontend",
    index: "01",
    title: "Front-End",
    description: "Interfaces that are fast, accessible, and built with modern React patterns.",
    items: ["JavaScript", "TypeScript", "React", "Next.js", "HTML", "CSS", "Tailwind"],
  },
  {
    id: "backend",
    index: "02",
    title: "Back-End",
    description: "APIs and services designed for reliability, security, and clear boundaries.",
    items: ["Go", "Node.js", "C", "REST", "JWT", "Docker", "Edge Functions", "Serverless", "Microservices"],
  },
  {
    id: "data",
    index: "03",
    title: "Data",
    description: "Structured data modeling, queries, and integration across application layers.",
    items: ["SQL", "PostgreSQL", "Supabase", "NoSQL"],
  },
  {
    id: "architecture",
    index: "04",
    title: "Architecture",
    description: "Enterprise strategy, API management, and systems that scale with the business.",
    items: [
      "AI Models & Agents",
      "Enterprise Architecture",
      "API Management",
      "Machine Learning & LLMs",
      "Network Security & Segmentation",
      "Google Cloud",
      "Azure Cloud",
      "AWS",
      "Disaster Recovery & Fault Tolerance",
    ],
  },
  {
    id: "design",
    index: "05",
    title: "Design",
    description: "Creating visual content for user interfaces and marketing materials.",
    items: ["Figma", "Capcut", "Canva", "Adobe XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro"],
  },
]
