[build]
  command = "npm run build"
  commandOrigin= "config"
  publish = ".next"
  publishOrigin = "config"

[[plugins]]
  origin = "config"
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = '/_next/image/*'
query = { q = ':quality', url = ':url', w = ':width' }
to = '/.netlify/images?url=:url&w=:width&q=:quality'
status = 200
force = true